### PR TITLE
WIP: prefer interface type instead of class

### PR DESCRIPTION
**Pull request by andrej-sajenko**
Hi,

should not we use the QueryCompiler Interface as property type instead of the DefaultQueryCompiler type?

### CODE REVIEW

**Comment by michel-kraemer** [comment]
Actually not. If you add this method to the interface you'll have to implement it in all indexer factories. That's actually the reason why your build fails by the way.

Why do you need the method in the interface?

**Comment by andrej-sajenko** [comment]
I am looking for a good place where i can extend or replace the DefaultQueryCompiler.
The elasticsearch analyser which i use, does not work with the generated bool query.

GET /georocket/_search
```
{
    "query": {
       "bool":{
          "should":[
             {
                "term":{
                   "tags":"trees"
                }
             },
             {
                "term":{
                   "is_encrypted":"trees"
                }
             },
             {
                "term":{
                   "featureType":"trees"
                }
             },
             {
                "multi_match":{
                   "query":"trees",
                   "fields":[
                      "genAttrs.*"
                   ]
                }
             },
             {
                "term":{
                   "gmlIds":"trees"
                }
             }
          ]
       }
    }
}
```

Elasticsearch will trigger the analyser, If i add the new property "featureType" to multi_math.fields

The term query does not allow elasticsearch to use the analyser, because of that i can not find any data if the values does not match exactly.

**Comment by michel-kraemer** [comment]
The indexer factory is a query compiler you can add new queries there. Why do you need the path in addition to the search string? I don't see the path in your example.

If you don't want to trigger the analyser for a certain attribute then set it's type to `keyword` in your mapping.

**Comment by andrej-sajenko** [comment]
_`The indexer factory is a query compiler you can add new queries there.`_
ok

I not need the path, this pull request should only show where i intended to make a change.

I want the analyzer to trigger for the featureType attribute. 

I found something which should solve my problem

```
  public JsonObject compileQuery(String search) {
    // match values of all fields regardless of their name
    return ElasticsearchQueryHelper.multiMatchQuery(search, "featureType");
  }
```

Thank you

**Comment by michel-kraemer** [comment]
You're welcome. Can the PR be closed?

**Pull request closed without merging**
