### PR TITLE
ContentType relations

### PR DESCRIPTION
**Pull request by andrej-sajenko**
Hey, i created a ContentType class which parse a plain content type "text/xml".
With it we can extract the parts type/specific+subtype;params from the content type
and check if the content type has a relation to another one.

application/gml+xml belongs to application/xml

So we can support application/xml and every specific xml format like
* application/gml+xml
* application/example+xml
will be supported as well.

### CODE REVIEW

**Comment by michel-kraemer** [comment]
This looks certainly useful. 👍

I have a couple of questions though:

* How does it improve the way GeoRocket handles Content-Types at the moment? I haven't had a problem importing XML files yet. Which client produces `application/gml+xml`?
* Is the terminology correct? https://en.wikipedia.org/wiki/Media_type specifies other terms for the individual parts of the media type.
* There is no library handling media types yet? I'd rather use a library than reinvent the wheel.

**Comment by michel-kraemer** [comment]
How about this?

    boolean belongsTo(String contentType, String type, String subtype) {
        return contentType.startsWith(type + "/") &&
            (contentType.endsWith("/" + subtype) || contentType.endsWith("+" + subtype));
    }

**Comment by michel-kraemer** [comment]
Alternatively, if you want to make sure only valid content type are accepted you could use this:

```java
boolean belongsTo(String contentType, String type, String subtype) {
    Pattern p = Pattern.compile(type + "/(\\w+\\+)?" + subtype);
    return contentType.matches(p);
}
```

You may have to improve the regex so that parameters and trees are handled correctly.

**Comment by andrej-sajenko** [comment]
> How does it improve the way GeoRocket handles Content-Types at the moment? I haven't had a problem importing XML files yet. Which client produces application/gml+xml?

I had the problem that one client included the charset parameter and the simple string comparison did not match the right content type. That is the reason i want to replace the switch case with an better way. You are right, we should use a supported library for this. I will look for one.

> Is the terminology correct? https://en.wikipedia.org/wiki/Media_type specifies other terms for the individual parts of the media type.

From the http terminology a content type is a mime "Multipurpose Internet Mail Extensions" [rfc2045](https://tools.ietf.org/html/rfc2045)
src: https://tools.ietf.org/html/rfc7231#section-3.1.1.5

The RFC 7231 contains a short definition.

> media-type = type "/" subtype *( OWS ";" OWS parameter )
>     type       = token
>     subtype    = token
>     [...]
>    parameter      = token "=" ( token / quoted-string )
 
src: https://tools.ietf.org/html/rfc7231#section-3.1.1.1

It is common to specify the specific types for application/xml
by prefix the subtype with the spefic type for your own (xml) sub format like gml.
See: http://www.iana.org/assignments/media-types/media-types.xhtml
But the specific type is a part of the subtype.
I got the name "specific type" from Stefan Tilkov's Book "REST und HTTP".

RFC 6838 which obsulates RFC 4288 and 2048 (part of the Multipurpose Internet Mail Extensions) introduce the method as a "structured syntax specifier suffix".

> [...]
> Similarly, the final "+" in a subtype name introduces a structured
> syntax specifier suffix.  Structured syntax suffix requirements are
>  specified in Section 4.2.8.

src: https://tools.ietf.org/html/rfc6838#section-4.2

  
> There is no library handling media types yet? I'd rather use a library than reinvent the wheel.

👍 I always find libraries which are a part of a framework.

**Comment by michel-kraemer** [comment]
Let's discuss this in depth the day after tomorrow when we meet in person.

**Comment by michel-kraemer** [comment]
Superseded by #50

**Pull request closed without merging**
